

import { MapConfig, VisualConfig, NodeTypeConfig, Theme } from './types';

export const DEFAULT_MAP_CONFIG: MapConfig = {
    orientation: 'vertical',
    numRows: 5,
    minNodesPerRow: 2,
    maxNodesPerRow: 4,
    bossRow: 3,
    hasIntermediateBoss: true,
    spacingX: 120,
    spacingY: 140,
    maxConnectionReach: 2,
    randomizeNodePositions: false, // Default to straight grid
    jitterIntensity: 40 // Default 40% intensity
};

export const DEFAULT_VISUAL_CONFIG: VisualConfig = {
    nodeShape: 'circle',
    showFloorNumber: true,
    showIcon: true,
    lineColorDefault: '#64748b',
    lineColorOutgoing: '#22c55e',
    lineColorIncoming: '#3b82f6',
    theme: 'default',
    connectionGap: 5,
    globalGlowEnabled: true // Default to showing glow
};

export const DEFAULT_NODE_TYPES: Record<string, NodeTypeConfig> = {
    start: { name: 'Start', color: '#10b981', icon: 'fas fa-door-open', editable: true, isFixed: true, iconColor: '#FFFFFF' },
    boss: { name: 'Final Boss', color: '#ef4444', icon: 'fas fa-skull', editable: true, isFixed: true, iconColor: '#FFFFFF' },
    normal: { name: 'Battle', color: '#334155', icon: 'fa-solid fa-dice-d20', editable: true, isFixed: false, iconColor: '#FFFFFF' },
    elite: { name: 'Elite', color: '#eab308', icon: 'fas fa-hand-fist', editable: true, isFixed: false, iconColor: '#FFFFFF' },
    event: { name: 'Event', color: '#3b82f6', icon: 'fas fa-scroll', editable: true, isFixed: false, iconColor: '#FFFFFF' },
    shop: { name: 'Shop', color: '#a855f7', icon: 'fas fa-shopping-cart', editable: true, isFixed: false, iconColor: '#FFFFFF' },
    treasure: { name: 'Treasure', color: '#f97316', icon: 'fas fa-gem', editable: true, isFixed: false, iconColor: '#FFFFFF' },
    mini_boss_editable: { name: 'Mini-Boss', color: '#6366f1', icon: 'fas fa-mask', editable: true, isFixed: false, iconColor: '#FFFFFF' }
};

export const ICON_LIST = [
    'fas fa-road', 'fa-solid fa-dice-d20', 'fas fa-hand-fist', 'fas fa-scroll', 'fas fa-shopping-cart', 'fas fa-gem', 
    'fas fa-mask', 'fas fa-flask', 'fas fa-heart', 'fas fa-fire', 'fas fa-shield-alt',
    'fas fa-hat-wizard', 'fas fa-dragon', 'fas fa-meteor', 'fas fa-compass', 'fas fa-bolt',
    'fas fa-campground', 'fas fa-dungeon', 'fas fa-ghost'
];

export const THEMES: Record<string, Theme> = {
    default: {
        start: '#10b981', boss: '#ef4444', normal: '#334155', elite: '#eab308', event: '#3b82f6',
        shop: '#a855f7', treasure: '#f97316', mini_boss_editable: '#6366f1'
    },
    dark: {
        start: '#059669', boss: '#991b1b', normal: '#0f172a', elite: '#b45309', event: '#1d4ed8',
        shop: '#7e22ce', treasure: '#c2410c', mini_boss_editable: '#4338ca'
    },
    pastel: {
        start: '#86efac', boss: '#fca5a5', normal: '#94a3b8', elite: '#fde047', event: '#93c5fd',
        shop: '#d8b4fe', treasure: '#fdba74', mini_boss_editable: '#a5b4fc'
    },
    cyberpunk: {
        start: '#00ffcc', boss: '#ff0055', normal: '#111111', elite: '#ffcc00', event: '#00ccff',
        shop: '#cc00ff', treasure: '#ff6600', mini_boss_editable: '#3300ff'
    }
};

export const TRANSLATIONS: any = {
    en: {
        layout: "Layout",
        visuals: "Visuals",
        structure: "Structure",
        orientation: "Orientation",
        vertical: "Vertical (Top-Down)",
        horizontal: "Horizontal (Left-Right)",
        floors: "Floors",
        reach: "Reach",
        minNodes: "Min Nodes",
        maxNodes: "Max Nodes",
        enableBossFloor: "Enable Intermediate Boss",
        bossFloor: "Intermediate Boss Floor",
        spacing: "Spacing",
        spacingX: "X Spacing",
        spacingY: "Y Spacing",
        randomizeLayout: "Stylized Layout (Jitter)",
        jitterIntensity: "Messiness Level",
        generate: "Generate New Map",
        updateLayout: "Update Layout Only",
        style: "Style",
        shape: "Shape",
        circle: "Circle",
        square: "Square",
        transparent: "Icon Only",
        showFloor: "Floor #",
        showIcons: "Icons",
        showGlow: "Show Glow",
        lines: "Lines",
        lineGap: "Connection Gap",
        default: "Default",
        incoming: "Incoming",
        outgoing: "Outgoing",
        theme: "Theme Preset",
        editRoomTypes: "Edit Room Types",
        reset: "Factory Reset",
        fit: "Fit",
        import: "Import JSON",
        export: "Export JSON",
        saveAs: "Save As",
        editNode: "Edit Node",
        floor: "Floor",
        locked: "Locked",
        unlocked: "Unlocked",
        roomType: "Room Type",
        icon: "Icon",
        customIcon: "Custom Icon Class",
        size: "Size",
        glow: "Glow",
        border: "Border Override",
        resetDefault: "Reset to Default",
        connections: "Next Floor Connections",
        noConnections: "No next floor.",
        promote: "Promote to Mini-Boss Hub",
        delete: "Delete",
        cancel: "Cancel",
        save: "Save",
        typeConfig: "Type Configuration",
        nodeColor: "Node Color",
        iconColor: "Icon Color",
        defaultIcon: "Default Icon",
        done: "Done",
        confirmReset: "Factory Reset: This will clear all data and revert to defaults. Continue?",
        help: "Help",
        helpTitle: "Full User Guide",
        
        // Help Section - Controls
        helpControlsTitle: "Controls & Navigation",
        ctrlMoveNode: "Move Room",
        ctrlMoveNodeDesc: "Hold Left Click on a room + Drag",
        ctrlEditNode: "Edit Room",
        ctrlEditNodeDesc: "Right Click on a room",
        ctrlPanMap: "Pan Map",
        ctrlPanMapDesc: "Hold Left Click on background + Drag",
        ctrlZoom: "Zoom",
        ctrlZoomDesc: "Mouse Wheel or Toolbar Buttons",
        
        // Help Section - Workflow
        helpWorkflowTitle: "Workflow & Features",
        featGenTitle: "Generation vs. Update",
        featGenDesc: "'Generate' creates a completely new map structure. 'Update Layout' keeps your current rooms but rearranges positions (useful after changing Orientation).",
        featLockTitle: "Locking Nodes",
        featLockDesc: "Inside the Edit menu (Right Click), you can LOCK a node. Locked nodes are NOT deleted when you click 'Generate New Map', allowing you to preserve specific rooms.",
        featChaosTitle: "Stylized Layout",
        featChaosDesc: "Enable 'Stylized Layout' in the sidebar to add organic irregularity (jitter) to the grid. Use the slider to control the messiness.",

        iconTip: "To get other icons use the site",
        addRoomType: "Add Room Type",
        deleteRoomType: "Delete Type",
        selectIcon: "Select Icon",
        addIcon: "Add Icon to Collection",
        iconClassPlaceholder: "e.g. fa-solid fa-dragon",
        back: "Back",
        applyToAll: "Apply color to all"
    },
    pt: {
        layout: "Layout",
        visuals: "Visuais",
        structure: "Estrutura",
        orientation: "Orientação",
        vertical: "Vertical (Cima-Baixo)",
        horizontal: "Horizontal (Esq-Dir)",
        floors: "Andares",
        reach: "Alcance",
        minNodes: "Min Salas",
        maxNodes: "Max Salas",
        enableBossFloor: "Habilitar Chefe Interm.",
        bossFloor: "Andar Chefe Interm.",
        spacing: "Espaçamento",
        spacingX: "Espaço X",
        spacingY: "Espaço Y",
        randomizeLayout: "Layout Estilizado (Torto)",
        jitterIntensity: "Nível de Bagunça",
        generate: "Gerar Novo Mapa",
        updateLayout: "Atualizar Layout",
        style: "Estilo",
        shape: "Formato",
        circle: "Círculo",
        square: "Quadrado",
        transparent: "Apenas Ícone",
        showFloor: "Nº Andar",
        showIcons: "Ícones",
        showGlow: "Exibir Brilho",
        lines: "Linhas",
        lineGap: "Distância da Borda",
        default: "Padrão",
        incoming: "Entrada",
        outgoing: "Saída",
        theme: "Tema",
        editRoomTypes: "Editar Tipos",
        reset: "Resetar Fábrica",
        fit: "Ajustar",
        import: "Importar JSON",
        export: "Exportar JSON",
        saveAs: "Salvar Como",
        editNode: "Editar Sala",
        floor: "Andar",
        locked: "Travado",
        unlocked: "Destravado",
        roomType: "Tipo de Sala",
        icon: "Ícone",
        customIcon: "Classe de Ícone Custom",
        size: "Tamanho",
        glow: "Brilho",
        border: "Cor da Borda",
        resetDefault: "Resetar Padrão",
        connections: "Conexões Próximo Andar",
        noConnections: "Sem próximo andar.",
        promote: "Promover a Mini-Boss",
        delete: "Excluir",
        cancel: "Cancelar",
        save: "Salvar",
        typeConfig: "Configuração de Tipos",
        nodeColor: "Cor do Nó",
        iconColor: "Cor do Ícone",
        defaultIcon: "Ícone Padrão",
        done: "Concluir",
        confirmReset: "Reset de Fábrica: Isso apagará todos os dados e voltará ao padrão. Continuar?",
        help: "Ajuda",
        helpTitle: "Guia Completo",

        // Help Section - Controls
        helpControlsTitle: "Controles e Navegação",
        ctrlMoveNode: "Mover Sala",
        ctrlMoveNodeDesc: "Segure Clique Esquerdo na sala + Arrastar",
        ctrlEditNode: "Editar Sala",
        ctrlEditNodeDesc: "Clique Direito na sala",
        ctrlPanMap: "Mover Mapa",
        ctrlPanMapDesc: "Segure Clique Esquerdo no fundo + Arrastar",
        ctrlZoom: "Zoom",
        ctrlZoomDesc: "Roda do Mouse ou botões na barra",

        // Help Section - Workflow
        helpWorkflowTitle: "Fluxo e Funcionalidades",
        featGenTitle: "Gerar vs. Atualizar",
        featGenDesc: "'Gerar' cria um mapa totalmente novo. 'Atualizar Layout' mantém suas salas atuais mas recalcula as posições (útil ao mudar Orientação ou Espaçamento).",
        featLockTitle: "Travando Salas (Lock)",
        featLockDesc: "No menu de edição (Clique Direito), você pode TRAVAR uma sala. Salas travadas NÃO são excluídas ao clicar em 'Gerar Novo Mapa', permitindo preservar salas específicas.",
        featChaosTitle: "Layout Estilizado",
        featChaosDesc: "Ative 'Layout Estilizado' na barra lateral para adicionar irregularidade orgânica (bagunça) ao grid. Use o slider para controlar o nível de caos.",

        iconTip: "Para pegar outros ícones use o site",
        addRoomType: "Adicionar Tipo de Sala",
        deleteRoomType: "Excluir Tipo",
        selectIcon: "Selecionar Ícone",
        addIcon: "Adicionar Ícone à Coleção",
        iconClassPlaceholder: "ex: fa-solid fa-dragon",
        back: "Voltar",
        applyToAll: "Aplicar cor a todos"
    },
    es: {
        layout: "Diseño",
        visuals: "Visuales",
        structure: "Estructura",
        orientation: "Orientación",
        vertical: "Vertical (Arriba-Abajo)",
        horizontal: "Horizontal (Izq-Der)",
        floors: "Pisos",
        reach: "Alcance",
        minNodes: "Mín Salas",
        maxNodes: "Máx Salas",
        enableBossFloor: "Habilitar Jefe Interm.",
        bossFloor: "Piso Jefe Interm.",
        spacing: "Espaciado",
        spacingX: "Espacio X",
        spacingY: "Espacio Y",
        randomizeLayout: "Diseño Estilizado (Irregular)",
        jitterIntensity: "Nivel de Desorden",
        generate: "Generar Nuevo Mapa",
        updateLayout: "Actualizar Diseño",
        style: "Estilo",
        shape: "Forma",
        circle: "Círculo",
        square: "Cuadrado",
        transparent: "Solo Ícono",
        showFloor: "Nº Piso",
        showIcons: "Íconos",
        showGlow: "Mostrar Brillo",
        lines: "Líneas",
        lineGap: "Distancia del Borde",
        default: "Predeterminado",
        incoming: "Entrada",
        outgoing: "Salida",
        theme: "Tema",
        editRoomTypes: "Editar Tipos",
        reset: "Restablecer",
        fit: "Ajustar",
        import: "Importar JSON",
        export: "Exportar JSON",
        saveAs: "Guardar Como",
        editNode: "Editar Sala",
        floor: "Piso",
        locked: "Bloqueado",
        unlocked: "Desbloqueado",
        roomType: "Tipo de Sala",
        icon: "Ícono",
        customIcon: "Clase de Ícono",
        size: "Tamaño",
        glow: "Brillo",
        border: "Borde Personalizado",
        resetDefault: "Restablecer",
        connections: "Conexiones Siguiente Piso",
        noConnections: "No hay piso siguiente.",
        promote: "Promover a Mini-Jefe",
        delete: "Eliminar",
        cancel: "Cancelar",
        save: "Guardar",
        typeConfig: "Configuración de Tipos",
        nodeColor: "Color de Nodo",
        iconColor: "Color de Ícono",
        defaultIcon: "Ícono Predeterminado",
        done: "Listo",
        confirmReset: "Restablecer: Esto borrará todos los datos. ¿Continuar?",
        help: "Ayuda",
        helpTitle: "Guía Completa",

        // Help Section - Controls
        helpControlsTitle: "Controles y Navegación",
        ctrlMoveNode: "Mover Sala",
        ctrlMoveNodeDesc: "Mantener Clic Izquierdo en sala + Arrastrar",
        ctrlEditNode: "Editar Sala",
        ctrlEditNodeDesc: "Clic Derecho en la sala",
        ctrlPanMap: "Mover Mapa",
        ctrlPanMapDesc: "Mantener Clic Izquierdo en fondo + Arrastar",
        ctrlZoom: "Zoom",
        ctrlZoomDesc: "Rueda del Ratón o botones",

        // Help Section - Workflow
        helpWorkflowTitle: "Flujo y Funciones",
        featGenTitle: "Generar vs. Actualizar",
        featGenDesc: "'Generar' crea un mapa nuevo. 'Actualizar Diseño' mantiene tus salas pero recalcula posiciones (útil al cambiar Orientación).",
        featLockTitle: "Bloquear Salas (Lock)",
        featLockDesc: "En el menú de edición (Clic Derecho), puedes BLOQUEAR una sala. Las salas bloqueadas NO se borran al 'Generar Nuevo Mapa'.",
        featChaosTitle: "Diseño Estilizado",
        featChaosDesc: "Activa 'Diseño Estilizado' para añadir irregularidad orgánica a la cuadrícula. Usa el deslizador para controlar el desorden.",

        iconTip: "Para obtener otros íconos use el sitio",
        addRoomType: "Añadir Tipo de Sala",
        deleteRoomType: "Borrar Tipo",
        selectIcon: "Seleccionar Ícono",
        addIcon: "Añadir Ícono a la Colección",
        iconClassPlaceholder: "ej: fa-solid fa-dragon",
        back: "Volver",
        applyToAll: "Aplicar color a todos"
    }
};